//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinectMicrophone.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KinectMicrophone.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;grammar version=&quot;1.0&quot; xml:lang=&quot;ru&quot; root=&quot;topLevel&quot;
        /// xmlns=&quot;http://www.w3.org/2001/06/grammar&quot;&gt;
        ///
        ///  &lt;rule id=&quot;topLevel&quot;&gt;
        ///    &lt;one-of&gt;
        ///      &lt;item&gt;&lt;ruleref uri=&quot;#управление_светом&quot; /&gt;&lt;/item&gt;
        ///	  &lt;item&gt;&lt;ruleref uri=&quot;#запрос_региорна&quot; /&gt;&lt;/item&gt;
        ///	&lt;/one-of&gt;
        ///  &lt;/rule&gt;
        ///
        ///  &lt;rule id=&quot;запрос_региорна&quot;&gt;
        ///    &lt;item&gt; что за регион &lt;/item&gt;  
        ///	&lt;ruleref uri=&quot;#числа_00_999&quot; /&gt;
        ///  &lt;/rule&gt;
        ///  
        ///  &lt;rule id=&quot;числа_00_999&quot;&gt;
        ///    &lt;item repeat=&quot;2-3&quot;&gt;
        ///      &lt;one-of&gt;
        ///	    &lt;item&gt; ноль &lt;/item&gt; 
        ///	    &lt;item&gt; один &lt;/item&gt; 
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string car {
            get {
                return ResourceManager.GetString("car", resourceCulture);
            }
        }
    }
}
